# Generated by Django 4.0 on 2021-12-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_quran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quran',
            name='audio',
            field=models.FileField(upload_to='media/'),
        ),
    ]
