# Generated by Django 4.0 on 2021-12-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_quran_audio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quran',
            new_name='Surah',
        ),
    ]
