# Generated by Django 4.0 on 2021-12-16 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_quran_surah'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
