# Generated by Django 4.0 on 2021-12-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_user_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chat_id',
        ),
    ]
