# Generated by Django 4.0 on 2021-12-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('uz', "O'zbek")], default=None, max_length=2, null=True),
        ),
    ]
