# Generated by Django 4.0 on 2021-12-31 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_reciter_id_alter_surah_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='surah',
            name='reciter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.reciter'),
        ),
    ]
