# Generated by Django 4.0 on 2021-12-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_surah_reciter'),
    ]

    operations = [
        migrations.AddField(
            model_name='surah',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surah',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
