# Generated by Django 4.0 on 2022-02-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_reciter_options_alter_surah_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('heading', models.CharField(blank=True, max_length=250, null=True)),
                ('body', models.TextField(blank=True, default=None, null=True)),
                ('image_id', models.IntegerField(blank=True, null=True)),
                ('media', models.ImageField(upload_to='media/posts/')),
            ],
        ),
        migrations.AlterField(
            model_name='surah',
            name='audio',
            field=models.FileField(upload_to='media/surahs/'),
        ),
    ]
