# Generated by Django 4.0 on 2022-01-16 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_surah_uuid_alter_surah_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surah',
            name='id',
        ),
        migrations.AlterField(
            model_name='surah',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
