# Generated by Django 4.0 on 2022-02-01 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_post_alter_surah_audio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
