# Generated by Django 4.0 on 2022-01-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_surah_id_alter_surah_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surah',
            old_name='uuid',
            new_name='id',
        ),
    ]
